from __future__ import annotations

TEMPLATES = [
    {
        "code": "env_record",
        "title": "6.1 環境監控記錄表",
        "description": "依目前環境監控資料整理每日監控記錄。",
        "requires": ["env_records"],
        "bundle": False,
        "downstream": ["env_monthly_pack"],
        "includes": [],
    },
    {
        "code": "env_monthly_pack",
        "title": "6 工作環境監控月報包",
        "description": "一次產生環境監控月報摘要與 6.1 環境監控記錄表明細。",
        "requires": ["env_records"],
        "bundle": True,
        "downstream": [],
        "includes": ["env_record"],
    },
    {
        "code": "production_daily",
        "title": "11.5 生產日報表",
        "description": "將目前生產批次整理成生產日報。",
        "requires": ["prod_records"],
        "bundle": False,
        "downstream": ["shipment_order_143", "shipping_pack"],
        "includes": [],
    },
    {
        "code": "quality_incoming",
        "title": "12.1 品質管理記錄表(原料)",
        "description": "將進料檢驗資料整理成原料品質記錄。",
        "requires": ["quality_records"],
        "bundle": False,
        "downstream": ["shipping_inspection_125"],
        "includes": [],
    },
    {
        "code": "material_request_112",
        "title": "11.2 領料單",
        "description": "依出貨或生產需求產生領料單草稿。",
        "requires": ["shipment_request"],
        "bundle": False,
        "downstream": [],
        "includes": [],
    },
    {
        "code": "shipment_order_143",
        "title": "14.3 出貨單",
        "description": "依訂單與 LOT 產生出貨單草稿。",
        "requires": ["shipment_request"],
        "bundle": False,
        "downstream": ["shipping_pack"],
        "includes": [],
    },
    {
        "code": "shipping_inspection_125",
        "title": "12.5 出貨檢查紀錄表",
        "description": "依訂單與品質資料整理出貨檢查紀錄。",
        "requires": ["shipment_request"],
        "bundle": False,
        "downstream": ["shipping_pack"],
        "includes": [],
    },
    {
        "code": "shipping_check_145",
        "title": "14.5 出貨檢查表",
        "description": "依出貨資料產生出貨前檢查表。",
        "requires": ["shipment_request"],
        "bundle": False,
        "downstream": ["shipping_pack"],
        "includes": [],
    },
    {
        "code": "shipping_pack",
        "title": "出貨流程紀錄包",
        "description": "一次產生出貨單、出貨檢查紀錄與出貨檢查表。",
        "requires": ["shipment_request"],
        "bundle": True,
        "downstream": [],
        "includes": ["shipment_order_143", "shipping_inspection_125", "shipping_check_145"],
    },
    {
        "code": "cip_152",
        "title": "15.2 製程缺陷追蹤改善(CIP)紀錄表",
        "description": "依不符合資料整理成 CIP 改善追蹤表。",
        "requires": ["nonconformance"],
        "bundle": False,
        "downstream": ["cip_pack"],
        "includes": [],
    },
    {
        "code": "cip_pack",
        "title": "CIP / 不符合流程包",
        "description": "一次產生 CIP 紀錄表與不符合來源摘要。",
        "requires": ["nonconformance"],
        "bundle": True,
        "downstream": [],
        "includes": ["cip_152"],
    },
    {
        "code": "audit_notice",
        "title": "17.4 內部稽核矯正通知單",
        "description": "依內部稽核計畫與稽核結果整理出稽核矯正通知。",
        "requires": ["audit_plans"],
        "bundle": False,
        "downstream": ["audit_pack"],
        "includes": [],
    },
    {
        "code": "audit_pack",
        "title": "內部稽核附件包",
        "description": "依年度稽核計畫整理內部稽核通知與必要附件。",
        "requires": ["audit_plans"],
        "bundle": True,
        "downstream": [],
        "includes": ["audit_notice"],
    },
    {
        "code": "management_review_pack",
        "title": "管理審查流程包",
        "description": "彙整品質目標、稽核、不符合與相關證據資料，作為管理審查附件包。",
        "requires": [],
        "bundle": True,
        "downstream": [],
        "includes": [],
    },
]

KEYWORDS = {
    "env_record": ["環境", "監控", "工作環境", "粒子"],
    "env_monthly_pack": ["環境月報", "監控月報", "工作環境月報", "環境監控月報", "粒子月報"],
    "shipping_pack": ["出貨流程", "出貨流程包", "出貨包", "出貨紀錄包", "出貨"],
    "shipment_order_143": ["出貨單", "出貨"],
    "shipping_inspection_125": ["出貨檢查紀錄", "出貨檢查", "檢查紀錄"],
    "shipping_check_145": ["出貨檢查表", "檢查表"],
    "material_request_112": ["領料", "領料單", "備料"],
    "cip_152": ["不符合", "改善", "cip", "矯正", "製程缺陷追蹤", "異常改善"],
    "cip_pack": ["cip 流程包", "不符合流程包", "cip 包", "改善流程包", "不符合包"],
    "production_daily": ["生產日報", "生產", "製程", "日報"],
    "quality_incoming": ["進料", "品質", "檢驗", "原料"],
    "audit_notice": ["內部稽核", "稽核矯正", "矯正通知", "稽核通知"],
    "audit_pack": ["稽核附件包", "內部稽核包", "稽核包", "年度稽核附件"],
    "management_review_pack": ["管理審查", "管理審查包", "review", "審查附件包"],
}
